"use client";

import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { useAuth } from "@/context/AuthContext";
import { getProgramsAll } from "@/supabase/actions/db-actions";
import { generateNameAvatar } from "@/utils/generateRandomAvatar";
import { Table } from "@tanstack/react-table";
import React, { useState } from "react";
import { exportProgramsToPDF } from "./programs-pdf";
import { toast } from "sonner";
import {
  Select,
  SelectItem,
  SelectContent,
  SelectValue,
  SelectTrigger,
} from "@/components/ui/select";
import { Loader2 } from "lucide-react";

export type ExportFormat = "pdf" | "csv" | "excel";

export interface ProgramsExportDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  globalFilter: any;
  filters: Record<string, string> | undefined;
  table: any;
  setOpenExport: (open: boolean) => void;
}

export default function ProgramsExportDialog({
  open,
  onOpenChange,
  globalFilter,
  filters,
  table,
  setOpenExport,
}: ProgramsExportDialogProps) {
  const [format, setFormat] = React.useState<ExportFormat>("pdf");
  const { userProfile, settings } = useAuth();
  const [loading, setLoading] = useState(false);

  const onConfirm = async () => {
    try {
      setLoading(true);
      // Pull all programs for the current search, filters and sorting (no pagination)
      const allPrograms = await getProgramsAll(
        typeof (globalFilter as any) === "string" ? (globalFilter as any) : "",
        userProfile?.id || "",
        userProfile?.roles?.name || "",
        userProfile?.agency_id || "",
        filters,
        // try to infer sorting from table state if present
        (table?.getState() as any)?.sorting?.[0]
          ? {
              sortBy: (table?.getState() as any)?.sorting?.[0]?.id,
              sortOrder: (table?.getState() as any)?.sorting?.[0]?.desc
                ? "desc"
                : "asc",
            }
          : {}
      );

      const up: any = userProfile as any;
      const organizationName =
        settings?.site_name ||
        up?.agency?.name ||
        up?.first_name + " " + up?.last_name ||
        "Daxow Agent Portal";
      const organizationLogo =
        settings?.logo_url ||
        up?.agency?.logo ||
        up?.profile ||
        generateNameAvatar(
          up?.first_name ||
            "" + " " + up?.last_name ||
            "" ||
            "Daxow Agent Portal"
        );
      const loggedInName =
        `${up?.first_name || ""} ${up?.last_name || ""}`.trim();
      const loggedInEmail = up?.email || "";
      const loggedInPhone = up?.phone || up?.mobile || "";

      const columns = [
        "Name",
        "University",
        "Faculty",
        "Speciality",
        "Degree",
        "Language",
        "Country",
        "City",
        "Created At",
      ];
      const mappedRows = (allPrograms || []).map((row: any) => [
        row?.name || "-",
        row?.zoho_universities?.name || "-",
        row?.zoho_faculty?.name || "-",
        row?.zoho_speciality?.name || "-",
        row?.zoho_degrees?.name || "-",
        row?.zoho_languages?.name || "-",
        row?.zoho_countries?.name || "-",
        row?.zoho_cities?.name || "-",
        row?.created_at ? new Date(row.created_at).toLocaleString() : "-",
      ]);

      if (format === "csv") {
        const headerLines = [
          `Organization: ${organizationName}`,
          `User: ${loggedInName}`,
          `Email: ${loggedInEmail}`,
          `Phone: ${loggedInPhone}`,
          "",
        ].join("\n");
        const csvHeader = columns.join(",");
        const csvRows = mappedRows
          .map((row) =>
            row
              .map((cell) => {
                const s = String(cell ?? "");
                const escaped = s.replace(/"/g, '""');
                return escaped.includes(",") ? `"${escaped}"` : escaped;
              })
              .join(",")
          )
          .join("\n");
        const csv = `${headerLines}${csvHeader}\n${csvRows}\n\nGenerated by: ${loggedInName} | ${loggedInEmail} | ${loggedInPhone}`;
        const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `programs_${Date.now()}.csv`;
        a.click();
        URL.revokeObjectURL(url);
      } else if (format === "excel") {
        const headerHtml = `
            <div style="display:flex;align-items:center;gap:12px;margin-bottom:12px;">
              <div style="font-weight:600;font-size:16px;">${organizationName}</div>
            </div>
          `;
        const footerHtml = `
            <div style="font-size:12px;margin-top:12px;border-top:1px solid #eee;padding-top:8px;">
              Generated by: ${loggedInName} | ${loggedInEmail} | ${loggedInPhone}
            </div>
          `;
        const tableHeader = `<tr>${columns.map((c) => `<th style='text-align:left;padding:6px;border:1px solid #ddd;'>${c}</th>`).join("")}</tr>`;
        const tableRows = mappedRows
          .map(
            (row) =>
              `<tr>${row.map((cell) => `<td style='padding:6px;border:1px solid #ddd;'>${String(cell ?? "")}</td>`).join("")}</tr>`
          )
          .join("");
        const html = `
            <html>
              <head><meta charset='UTF-8' /></head>
              <body>
                ${headerHtml}
                <table style='border-collapse:collapse;'>
                  <thead>${tableHeader}</thead>
                  <tbody>${tableRows}</tbody>
                </table>
                ${footerHtml}
              </body>
            </html>`;
        const blob = new Blob([html], {
          type: "application/vnd.ms-excel;charset=utf-8;",
        });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `programs_${Date.now()}.xls`;
        a.click();
        URL.revokeObjectURL(url);
      } else {
        await exportProgramsToPDF({
          organizationName,
          organizationLogo,
          loggedInName,
          loggedInEmail,
          loggedInPhone,
          programs: allPrograms || [],
          dateRangeText: `Generated on ${new Date().toLocaleString()}`,
        });
      }

      setOpenExport(false);
    } catch (err) {
      toast.error("Failed to export programs");
      console.error("Export error:", err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Export Programs</DialogTitle>
        </DialogHeader>
        <div className="space-y-2">
          <Select
            value={format}
            onValueChange={(value: string) => setFormat(value as ExportFormat)}
          >
            <SelectTrigger>
              <SelectValue placeholder="Select format" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="pdf">PDF</SelectItem>
              <SelectItem value="csv">CSV</SelectItem>
              <SelectItem value="excel">Excel</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <DialogFooter>
          <Button variant="ghost" size="sm" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button size="sm" onClick={() => onConfirm()} disabled={loading}>
            {loading ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Preparing...
              </>
            ) : (
              "Download"
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
